### ISSUE TITLE
Issue with `IQuerable<T>.SingleOrDefault(Predicate<T>)`

### ISSUE THREAD

**Issue by carusology** [invio/FSharp.MySqlQueryProvider#1]
When I tried to use `IQuerable<T>.SingleOrDefault(Predicate<T>)` for a queryable with a constraint that will correctly return zero or one items, the queryable throws an `InvalidOperationException` stating that more than one element exists in the collection.

Here's the stack trace of the relevant provider code:
```
System.InvalidOperationException : Sequence contains more than one element
Stack Trace:
     at FSharp.MySqlQueryProvider.DataReader.read(IDataReader reader, ConstructionInfo constructionInfo)
     at FSharp.MySqlQueryProvider.MySqlQueryProvider.Execute(Expression expression)
     at FSharp.MySqlQueryProvider.Queryable.QueryProvider.System-Linq-IQueryProvider-Execute[S](Expression expression)
     at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
```

Here's some code detailing the problem.

```
IQuerable<T> queryable = CreateQueryable<T>();

// This throws InvalidOperationException
var myFoo = queryable.SingleOrDefault(foo => foo.Property == "bar");

// Simple workaround. This works.
var myFoo = queryable.Where(foo => foo.Property == "bar").SingleOrDefault();
```

**Comment by rokadias** [comment]
Fixed in PR https://github.com/invio/FSharp.MySqlQueryProvider/pull/4
